### ISSUE TITLE
NAT64 not work

### ISSUE THREAD

**Issue by iamryanchia** [loxilb-io/loxilb#329] opened 2023-06-21 10:00 UTC
I run the following command to add a NAT64 rule, but it does not work.

`loxicmd create lb 2001:db8:dead:beef:fe::19a3 --tcp=8080:8081 --endpoints=192.168.122.248:1`

The guide [Configure load-balancer rule](https://loxilb-io.github.io/loxilbdocs/cmd/#configure-load-balancer-rule) also showes the command is the only need to be run. Do I miss some other commands to make NAT64 work?

When i try to connect the load balancer, I find some logs printed by loxilb:

```
17:50:01 TRACE loxilb_libdp.c:1660: ct: #2001:db8:dead:beef:fe::183f:58182 -> 2001:db8:dead:beef:fe::19a3:8080 (6)# rid:1 est:0 nat:1 (Aged:10394594605ns:0:0)
17:50:01 TRACE loxilb_libdp.c:1586: ct: rdir not found #192.168.122.174:58182 -> 192.168.122.248:8080 (6)#
```

My environment is `loxilb 0.8.7` and `ubuntu 20.04`.

**Comment by nik-netlox** [comment] 2023-06-21 10:33
Hi @iamryanchia,
We have a nat64 CICD test case which we have verified in github actions. It is working fine. Please check the logs here: https://github.com/nik-netlox/loxilb/actions/runs/5332875450/jobs/9662635915

There are some additional setting which you may have to do depending on your environment. I would suggest you to check and configure as per [this](https://github.com/loxilb-io/loxilb/blob/main/cicd/nat64tcp/) test case.
Please feel free to revert if you still face issues.

**Comment by iamryanchia** [comment] 2023-06-21 10:56
Thanks, I'll do what you suggest and post here if there is progress.

**Comment by iamryanchia** [comment] 2023-06-22 03:14
> Hi @iamryanchia, We have a nat64 CICD test case which we have verified in github actions. It is working fine. Please check the logs here: https://github.com/nik-netlox/loxilb/actions/runs/5332875450/jobs/9662635915
> 
> There are some additional setting which you may have to do depending on your environment. I would suggest you to check and configure as per [this](https://github.com/loxilb-io/loxilb/blob/main/cicd/nat64tcp/) test case. Please feel free to revert if you still face issues.

I have ran `validation.sh` on my host, it works fine. And I also test NAT64 in isolated net spaces created manually, it all works fine.

 I doubt there is difference between veth device and physical device.

Can you explain what does "rdir not found" means? And give some advices to debug?

**Comment by TrekkieCoder** [comment] 2023-06-22 03:25
For physical/bare-metal, I think you would need the following setting :
``` 
ethtool --offload {interface name} rx off tx off
```
If it does not work, please let us know output of this :

```
# ethtool -k {interface name} | grep check
```

Rdir not found simply means that connection could be established and LB session entries are expired.

**Comment by iamryanchia** [comment] 2023-06-22 04:43
Thanks for your reply. When I read the `config.sh` and compare with my own setup. I have ran `ethtool --offload ...` already.

Here is the output:

```
rx-checksumming: on [fixed]
tx-checksumming: off
        tx-checksum-ipv4: off [fixed]
        tx-checksum-ip-generic: off
        tx-checksum-ipv6: off [fixed]
        tx-checksum-fcoe-crc: off [fixed]
        tx-checksum-sctp: off [fixed]
```

The rx-checksumming can not be off warned by `ethtool`.

---

More specifically, I make experiment with loxilb on two KVMs, one as client and another as lb.

client ip: `192.168.122.248/24 2001:db8:dead:beef:fe::183f/128 fe80::6494:f0c0:e55d:d09c/6`
lb ip: `192.168.122.174/24 2001:db8:dead:beef:fe::19a3/128 fe80::aa6a:5f97:e2b0:887d/64`

So with the command mentioned at the beginning, i am trying to transform lb ipv6 to client ipv4. I use `nc` on client to connect lb:

```
nc -v 2001:db8:dead:beef:fe::19a3 8080
```

and listen on 8081 on client to receive request:

```
nc -l 192.168.122.248 8081
```

It does not work.

`rdir not found #192.168.122.174:58182 -> 192.168.122.248:8080` shows it tries to connect client 8080. It is strange and makes me confued.

Maybe you can use two KVMs to reproduce this problem.

**Comment by TrekkieCoder** [comment] 2023-06-22 06:24
Thanks for digging deep. We reconfirmed in KVM Please try the following in loxilb after creating the LB rule -

```
loxicmd create ep  192.168.122.248 --name=192.168.122.248_tcp_8081 --probetype=ping
```

Another way to solve this issue is to add "monitor" flag while creating LB  - 
```
loxicmd create lb 2001:db8:dead:beef:fe::19a3 --tcp=8080:8081 --endpoints=192.168.122.248:1 --monitor
```
But the above way might cause nc server to exit. Because loxilb will do liveness check of the endpoint. But if you run real server app, there should be no problem. 

And regarding the log, I think there is a typo. Will check !!

**Comment by iamryanchia** [comment] 2023-06-22 08:06
Sorry, it still does not work. Are you sure it works after adding `--monitor`/`--probetype=ping`?

**Comment by iamryanchia** [comment] 2023-06-22 08:16
I replaced the `nc` with an echo server, I can see periodic connections from liveness check. But when i use `nc` to connect lb's ipv6 8080 port, no incoming connection.

**Comment by TrekkieCoder** [comment] 2023-06-22 08:19
Yes it works fine. The issue was sometimes end-point neighbor did not show up. So, if you see 192.168.122.248 entry in ```ip neigh``` of loxilb, it should be fine. Also,  I can see your ipv6 addresses are with 128 prefix e.g 2001:db8:dead:beef:fe::183f/128. Kindly make sure client<->loxilb are in same ipv6 subnet  e.g 2001:db8::1/64 and 2001:db8::2/64.  Can you double confirm by 
"tcpdump -vvv" on the "in" and "out" interface of loxilb ??

**Comment by TrekkieCoder** [comment] 2023-06-22 08:36
And one more thing the LB VIP should usually not be interface IP (in case of loxilb). So may be you can try the following hypothetical scenario -

<client1-2001:db8::2/64> --- < 2001:db8::1/64 loxilb 192.168.122.174/24> -- <server-192.168.122.248/24> 

Create LB using :
```
loxicmd create lb 3ffe::1 --tcp=8080:8081 --endpoints=192.168.122.248:1 --monitor
```

Add route in client for loxilb VIP :
```
ip -6 route add 3ffe::1/128 via 2001:db8::1
```

Try from client :
```
nc -v 3ffe::1 8080
```

**Comment by iamryanchia** [comment] 2023-06-22 08:54
Thanks, It works if i use 3ffe::1 as VIP, and route its traffic to lb on client!

Another question: If the ip is an external public ip, and bound to an interface. How can i use this ip as VIP? Is it required to remove the ip from interface.

**Comment by TrekkieCoder** [comment] 2023-06-23 01:11
Hi,

In the example topology which works, you can create another LB rule like this:

```
loxicmd create lb 2001:db8::1 --tcp=8080:8081 --endpoints=192.168.122.248:1 --monitor

```

And try from client :
```
nc -v 2001:db8::1 8080
```

**Comment by TrekkieCoder** [comment] 2023-07-02 03:31
The original issue is resolved. Marking this as closed !

**Closed by TrekkieCoder** 2023-07-02 03:31 UTC
